version: '3'

services:
  database:
    image: jawwadhabib/ca4-postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: jawwadhabib/ca4-app:latest
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@database:5432/mydb
    ports:
      - "3000:5000"
    depends_on:
      - database

volumes:
  postgres_data:
